/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from MyAwesomeLangTypeRules.sl
 */

#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

/**
 * This class was synthesized from the "MyAwesomeLangTypeRules" rules group.
 */
class MyAwesomeLangTypeRules
{
public:
    TypeCls StaticMethodDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code*);
};
