/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from ./demo/MyAwesomeLangTypeRules.sl
 */

#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

/**
 * This class was synthesized from the "MyAwesomeLangTypeRules" rules group.
 */
class MyAwesomeLangTypeRules
{
public:
    /**
     * This method was synthesized from the "StaticMethodDispatch" inference definition.
     */
    TypeCls StaticMethodDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code*);

};
