language: cpp

os:
  - ubuntu
  - osx

compiler:
  - clang

script:
  - uname -a
  - cmake --version
  - clang++ --version
  - g++ --version
  - python3 --version
  - make -C libs
  - mkdir build && cd build && cmake -DUSE_PRECOMPILED_PARSER=ON .. && make
  - echo "DONE"
