/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from /home/x/workspace/Snowlake/tests/./fixtures/computed_target_type.sl
 */

#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

/**
 * This class was synthesized from the "ComputedTargetType" rules group.
 */
class ComputedTargetType
{
public:
    /**
     * This method was synthesized from the "MethodStaticDispatch" inference definition.
     */
    TypeCls MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code*);

};
