/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from /home/x/workspace/Snowlake/tests/./fixtures/empty_group.sl
 */

#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

/**
 * This class was synthesized from the "EmptyGroup" rules group.
 */
class EmptyGroup
{
public:
};
