/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from /home/x/workspace/Snowlake/tests/./fixtures/empty_group.sl
 */

#include "EmptyGroup.h"
#include "InferenceErrorDefn.h"
