/**
 * Auto-generated by Snowlake compiler (version 0.1.2).
 */


#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

class FullFeature
{
public:
    TypeCls MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code*);

    TypeCls BinaryExpressionInference(const Expr& expr, std::error_code*);

};
