/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */
#include "InferenceErrorDefn.h"
#include <string>
#include <system_error>

class InferenceErrorCategory : public std::error_category
{
    virtual const char* name() const except override {
        return "Inference error";
    }

    virtual std::string message(int condition) const override {
        switch (condition) {
            case InferenceErrorInferredTypeMismatch:
                return "Inferred type does not match with expected.";
            case InferenceErrorTypeComparisonFailed:
                return "Type comparison failed.";
            default:
                return "Inference failed (unknown error).";
        }
    }
};

const InferenceErrorCategory inference_error_category {};
