/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */
#pragma once

enum InferenceError
{
    InferenceErrorInferredTypeMismatch = 0x01,
    InferenceErrorTypeComparisonFailed,
};

class InferenceErrorCategory;
extern const InferenceErrorCategory inference_error_category;
