/**
 * Auto-generated by Snowlake compiler (version 0.1.2).
 */


#include "ValidProposition.h"
#include "InferenceErrorDefn.h"

TypeCls
ValidProposition::MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code* err)
{
    TypeCls ReturnType = proveType(StaticMethodCallStmt.return_type);

    return ReturnType;
}
