/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */

/**
 * This file was synthesized from /home/x/workspace/Snowlake/tests/./fixtures/valid_proposition.sl
 */

#include "ValidProposition.h"
#include "InferenceErrorDefn.h"

/**
 * This method was synthesized from the "MethodStaticDispatch" inference definition.
 */
TypeCls
ValidProposition::MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code* err)
{
    // This corresponds to the 1st premise rule in the inference definition.
    TypeCls ReturnType = proveType(StaticMethodCallStmt.return_type);

    return ReturnType;
}
