/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */


#pragma once

#include <cstdlib>
#include <cstddef>
#include <vector>
#include <system_error>

class ValidSemantics
{
public:
    TypeCls MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code*);

};
