/**
 * Auto-generated by Snowlake compiler (version 0.1.1).
 */


#include "ValidSemantics.h"
#include "InferenceErrorDefn.h"

TypeCls
ValidSemantics::MethodStaticDispatch(const ASTExpr& StaticMethodCallStmt, std::error_code* err)
{
    std::vector<TypeCls> ArgumentsTypes = proveType(StaticMethodCallStmt.argument_types);

    if (!cmpType(ArgumentsTypes, SELF_TYPE, std::not_equal_to<TypeCls>())) {
        *err = std::error_code(0, inference_error_category);
        return TypeCls();
    }
    return lub(T1, T2);
}
